server:
  port: ${PORT:10000}
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false

plugins:
  - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"

youtube:
  enabled: true
  allowSearch: true
