server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false

  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"

plugins:
  youtube:
    enabled: true
