server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false

  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"

plugins:
  youtube:
    enabled: true
    allowSearch: true

  lavasrc:
    providers:
      - 'ytsearch:"%ISRC%"'
      - 'ytsearch:%QUERY%'

    sources:
      spotify: true
      youtube: false

    spotify:
      clientId: "3d37196b35574b8da2c64cd9906e252f"
      clientSecret: "e1dfff225b054970ad10c5041e929845"
